main: main.c insertion_sort.h insertion_sort.c merge_sort.h merge_sort.c allocator.h stdlib_allocator.c max_heap.h max_heap.c quick_sort.h quick_sort.c heap_sort.h heap_sort.c
	clang -Wall -Wextra -o main main.c insertion_sort.c merge_sort.c stdlib_allocator.c max_heap.c quick_sort.c heap_sort.c
